name: Build YouTube Reborn
on: push

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Setup Theos
        uses: beerpiss/theos-action@v1
      -
        name: Build
        run: |
          export TERM=xterm
          set -o pipefail
          gmake package FINALPACKAGE=1 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
