name: Build YouTube Reborn
on: push

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Setup Theos
        uses: beerpiss/theos-action@v1
      -
        name: Setup build environment
        run: |
          set -o pipefail

          echo TERM=xterm >> $GITHUB_ENV
          echo PKGNAME=$(grep '^Package:' control | cut -d' ' -f2-) >> $GITHUB_ENV
          echo PKGVER=$(grep '^Version:' control | cut -d' ' -f2-) >> $GITHUB_ENV
          echo PKGARCH=$(grep '^Architecture:' control | cut -d' ' -f2-) >> $GITHUB_ENV
          echo GIT_DATE=$(git show -s --format=%cs | tr -d "-") >> $GITHUB_ENV
          echo GIT_COMMIT_HASH=$(git rev-parse --short HEAD) >> $GITHUB_ENV

          mkdir -p out
      -
        name: Build (release)
        run: |
          gmake clean 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          gmake package FINALPACKAGE=1 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          mv packages/* out/
      - 
        name: Build (debug)
        run: |
          gmake clean 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          
          mkdir -p .theos/packages
          echo $(( $GITHUB_RUN_NUMBER - 1 )) > .theos/packages/$PKGNAME-$PKGVER+git$GIT_DATE.$GIT_COMMIT_HASH
          
          gmake package FINALPACKAGE=0 DEBUG=1 2>&1 | grep -Ev --line-buffered 'getcwd|descriptor'
          mv packages/* out/
      -
        name: Upload artifacts (release)
        uses: actions/upload-artifact@v3
        with:
          name: RELEASE
          path: out/${{ env.PKGNAME }}_${{ env.PKGVER }}_${{ env.PKGARCH }}.deb
      -
        name: Upload artifacts (debug)
        uses: actions/upload-artifact@v3
        with:
          name: DEBUG
          path: out/${{ env.PKGNAME }}_${{ env.PKGVER }}-debug.*+git*_${{ env.PKGARCH }}.deb
